= Monitoring Public APIs Versus Monitoring Private Ones

Monitors (both the test versions and the schedules that a monitor contains) are run by instances of Mule, and these instances are called _workers_. Each worker runs a single monitor.

A worker normally runs in one of CloudHub's twelve different _worker clouds_, each of these clouds corresponding to a geographic region. The complete list of regions is listed in the "Global Worker Clouds" section of the topic xref:runtime-manager::cloudhub-architecture.adoc[About CloudHub Architecture]. You can select a region available to you to run a worker in when you create a monitor, add a schedule to a monitor, or modify a monitor. Examples of names of worker clouds are `us-east-1` and `eu-central-1`.

Workers that run in a worker cloud and that run the monitors you create with API Functional Monitoring (AFM) can run tests only against APIs that are publicly accessible. They cannot access APIs that are in private networks. Moreover, the number of workers that you can run is limited. If you reach the limit, you must contact your MuleSoft administrator about raising your maximum.

However, if you have a subscription to Anypoint Virtual Private Cloud (VPC), workers that run your monitors virtual, private, and isolated network segment and can access APIs in your private network. You can also run as many as your allotment of vCores allows. Each worker consumes 0.2 vCores.

== Public Locations and Private Locations

In API Functional Monitoring, a _public location_ is one of the twelve worker clouds. When you select one of these as part of creating a monitor or as part of adding or editing a schedule, you are specifying that the API that you want the monitor to test or the schedule to run a test against is a public API. In addition, you are specifying that you want to allocate a worker from the limited number of workers that you can allocate.

A _private location_ is like a namespace in an instance of VPC that is configured to allow workers to access your private network. API Functional Monitoring can create workers within that namespace that can run tests against APIs that are accessible only within the network that VPC is configured for.

Before you can select a private location, you must create one, which involves specifying a name. For example, you might create a private location that you name `myLocation`. When you choose to run a monitor by using `myLocation`, API Functional Monitoring allocates a worker in one of the worker clouds that you have access to. That worker is able to access your private network through Anypoint Virtual Cloud and access

== Select a Public location When You Create a Monitor in Anypoint Monitoring

When you create a monitor, you create version 1.0.0 of the test that the monitor runs and the schedule for running the test. The fields under the heading *Execution location* are for configuring the schedule. In the *location* field, click the arrow and, in the menu that appears, select one of the options under the heading *Public locations*.


== Select a Public location When You Modify or Create a Schedule in Anypoint Monitoring

In an existing monitor, you can modify or add a schedule in the *Schedules* section.

* To the right of schedule listed in the table in this section, click the three dots and select *Modify* to open the Modify Schedule dialog.
* Click the *Add Schedule* button to open the Add Schedule dialog.

In either dialog, click the arrow in the *location* field and select one of the options under the heading *Public locations*.


== Specify a Public location When You Create a Monitor by Using the BAT CLI



== Select or Create a Private location When You Create a Monitor in Anypoint Monitoring


== Select or Create a Private location When You Create a Schedule in Anypoint Monitoring


== Specify a Private location When You Create a Monitor by Using the BAT CLI
