= View the Details of Past Executions of a Test
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: afm-view-test-history.adoc

:imagesdir: ../assets/images

You can review the details of past executions of a monitor's test.

== Procedure

. In the list of your monitors, select the monitor that includes the test.
. On the page that is opened, click the three dots next to the name of the monitor and select *View Monitor History*.
. On the *Monitor History* page, click the list entry for the test execution that you want to see the details of.
+
You can identify a test execution the following details in the list entries:
+
* Its sequential number
* Its result: Passed or Failed
* Its duration
* Its schedule
* The location from which the test was executed
* If the location was private, the environment in which the private location is located


== Results

// Will need to change this content according to the answer I receive about what is on the page in Iteration 2 that lists GET methods and endpoints.
The History page is opened for the test version. The page displays the status of each execution and statistics that are associated with it. The statistics are:

* When the test was last executed
* How long the execution lasted
* The location from which the test was run
* The environment from which the test was run

Click the *Details* button for one of the executions to see this information for each tested endpoint:

* The status of the test
* The length of time that passed before a response was received
* The type of request
* The headers in the request
* The headers in the response
* The results of the test assertions
