= Modify a Schedule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can modify a schedule if you want to change:

* The location in which the test is run from
* The frequency at which to run the test

== Before You Begin

If you want to modify a schedule to use a public location instead of a private one, ensure that your organization in Anypoint Platform has not reached its maximum number of schedules for public locations. An indicator at the top of the list of your monitors gives the count of public schedules that are already being used.

== Procedure


. In the list of your monitors, select the monitor in which you want to modify a schedule.
. Locate the schedule in the list.
. Click the three dots to the right of the list entry for the schedule.
. Select *Modify Schedule*.
. In the *Modify Schedule* dialog, make your changes.
. Click *Save*.

== Result

Changes take place after the current interval elapses. For example, if you change the interval of a schedule from every 15 minutes to every hour and the timer on the monitor shows that there are 5 minutes left in the current interval, the new interval goes into effect after the five minutes elapse and the test is run.

== See Also

* xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs]
* xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs and Mixes of Both Public and Private APIs]
