= Delete a Schedule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You might want to delete a schedule for any of the following reasons:

* You are finished testing endpoints of a public API and you want to free resources for testing endpoints of a different public API.
* You are finished testing endpoints of a private API.
* You have more than one schedule running the same test and you no longer need one of the schedules.

[IMPORTANT]
====
Be sure that you want to delete a schedule. AFM does not give you a chance to confirm that you want to delete it.
====

== Procedure

To delete a schedule from the *Schedules* section of a monitor:

. Select the monitor in which you want to modify a schedule.
. Click the *Schedules* tab.
. Find the schedule in the list, click the three dots on the right end of the table row, and select *Delete*.

To delete a schedule from the list of schedules that use a particular location:

. Display the list of locations by clicking the *Locations* tab at the top of the screen.
. Select the location that you want to use in a new schedule.
. Find the schedule in the list, click the three dots on the right end of the table row, and select *Delete*.

== Result

If the schedule that you deleted was the only schedule that was running a particular test, the worker for that test no longer exists.

If the schedule was one of two or more schedules that were running a particular test, the timer on the monitor matches the shortest value in the *Next Run* column of the monitor's table of schedules.

If the schedule was the only schedule that was using a private location, you can now delete that private location, if you want to do so.
