= Create a New Version of a Test

You cannot edit a test that you have already created for a monitor. However, you can create a new version of a test. In that new version, you can change, remove, or add assertions, headers, endpoints, and reporters.

The version number of the new test is the same as that for the previous test, but with the third part of the number incremented by 1. For example, if the version number of the original test is 1.0.0, the new version is at 1.0.1.

You can edit a test only if it has not been customized to include features that the *Create a Monitor from Scratch* page does not support. It is possible to customize a test by downloading it, editing it manually, and then uploading it. Tests created manually and then uploaded also are not editable if they contain features that the *Create a Monitor from Scratch* page does not support.

== Procedure

. Open the monitor that includes the test that you want to create a new version of.
. Click the *Tests* tab.
. Find the test and click the pencil icon directly beneath it.
. In the *Modify Existing Monitor* page, make your changes to the test.

== Result

After you click *Update*, a new version of the test is listed in the *Tests* section for the monitor.

The schedule that you created when you created the monitor now runs only the new version of the test. If you want to run previous versions of a test, you can create new schedules for them.
