= Create a Private Location
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images
 
A _private location_ is a worker that runs in a CloudHub environment associated with an Anypoint Virtual Private Cloud instance. You have the opportunity to create a private location when you:

* xref:afm-create-monitor.adoc[Create a monitor]
* xref:afm-add-schedule.adoc[Add a schedule] to a monitor
* xref:afm-modify-schedule.adoc[Modify a schedule] in a monitor

This procedure explains how to create a private location when you modify a schedule.

For information about private locations and their uses, see xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs].

== Before You Begin

Ensure that your Anypoint Platform organization has a subscription to Anypoint Virtual Private Cloud.

== Procedure

To create a private location:

. When creating a test or schedule, click the field under *Select location* and select *Create new location*.
. Name the location.
+
The name can be up to 255 characters, and can include spaces and special characters.
. Select the environment where the tests will run.
. Complete the creation of the of test or schedule.

== Result

The private location is added to the list of private locations. While API Functional Monitoring is registering the location, the status indicator for the location is yellow. After it is registered, if the environment in which the location was created is online, the location shows a green status indicator.

If the indicator is red, navigate to Runtime Manager and restart the environment. Then, check the logs for the environment to troubleshoot the problem that caused it to go offline.

== What to Do Next

You can now run tests from the private location, either by adding a schedule that uses the location or by modifying an existing schedule to use it.

== See Also

* xref:afm-create-monitor.adoc[Create a Monitor]
* xref:afm-add-schedule.adoc[Add a Schedule]
* xref:afm-modify-schedule.adoc[Modify a Schedule]
