= Monitoring the Endpoints of Public and Private APIs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

== Monitoring the Endpoints of Public APIs

Public APIs are APIs of which the endpoints are exposed on the open internet. In API Functional Monitoring (AFM), workers running in a public location run the monitors that you create to monitor the endpoints of public APIs. A _public location_ is a region in CloudHub that is shared with other MuleSoft customers.

Because the location is shared, the amount of resources that you can consume in it is limited, though you can increase the limits. Initially, AFM lets your organization in Anypoint Platform run up to five workers at one time. Therefore, you can monitor the endpoints of up to five public APIs at one time.

When you select one of these as part of creating a monitor or as part of adding or editing a schedule, you are specifying that the API that you want the monitor to test or the schedule to run a test against is a public API. In addition, you are specifying that you want to allocate a worker from the limited number of workers that you can allocate.

Workers that run in a worker cloud and that run the monitors you create with API Functional Monitoring (AFM) can run monitors that test only APIs that are publicly accessible. Such workers cannot access APIs that are in private networks.

Also, the number of workers that you can run at the same time in worker clouds is limited. For example, if your limit is five, the total number of workers that you can run simultaneously in worker clouds is five. If you run two in, say, `us-east-1` and three in `us-east-2`, you are still subject to the limit. You cannot run five in each worker cloud. If you reach the limit, you must contact your MuleSoft administrator about raising your maximum.

However, if you have a subscription to Anypoint Virtual Private Cloud (VPC), you can run workers in a virtual, private, and isolated network segment. These workers can access APIs in your private network. You can also run as many workers as your allotment of vCores allows. Each worker consumes 0.2 vCores.

== Public and Private Locations


A _private location_ is a namespace in an instance of VPC that is configured to allow workers to access your private network. AFM can create workers within that namespace that can run tests against APIs that are accessible only within the network that VPC is configured for. You can create multiple private locations in a single VPC.

Before you can select a private location, you must create one, which involves specifying a name. For example, you might create a private location that you name `myLocation`. When you choose to run a monitor in `myLocation`, AFM allocates a worker in Anypoint Virtual Cloud in the `myLocation` namespace.

== Select a Public location When You Create a Monitor in Anypoint Monitoring

When you create a monitor, you create version 1.0.0 of the test that the monitor runs and the schedule for running the test. The fields under the heading *Execution location* are for configuring the schedule. In the *location* field, click the arrow and, in the menu that appears, select one of the options under the heading *Public locations*.


== Select a Public location When You Modify or Create a Schedule in Anypoint Monitoring

In an existing monitor, you can modify or add a schedule in the *Schedules* section.

* To the right of schedule listed in the table in this section, click the three dots and select *Modify* to open the Modify Schedule dialog.
* Click the *Add Schedule* button to open the Add Schedule dialog.

In either dialog, click the arrow in the *location* field and select one of the options under the heading *Public locations*.


== Specify a Public location When You Create a Monitor by Using the BAT CLI



== Select or Create a Private location When You Create a Monitor in Anypoint Monitoring


== Select or Create a Private location When You Create a Schedule in Anypoint Monitoring


== Specify a Private location When You Create a Monitor by Using the BAT CLI
