= Create a Version of a Test from an Existing One
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

There are two methods by which you can create a version of an existing test in a monitor:

By using the interface in Anypoint Monitoring:: In the new version, you can change, remove, or add assertions, headers, endpoints, and reporters.

By editing a test manually and then uploading it to Anypoint Monitoring::
The interface in Anypoint Monitoring supports a subset of the functional-monitoring features that you can use if you write tests manually. If you have uploaded to Anypoint Monitoring a monitor that you created or edited manually, you might not be able to use the interface to create a version of a test in that monitor. If you receive an error message, you must create the new test manually.

== Procedure

* To create a version of an existing test by using the interface in Anypoint Monitoring:
.. Open the monitor that includes the test that you want to base a new test on.
.. Click the *Tests* tab.
.. Find the test and click the pencil icon directly beneath it.
.. In the *Modify Existing Monitor* page, make your changes to the test.

+
After you click *Update*, the new version is listed in the *Tests* section for the monitor.

* To create a version of a test by editing the existing test manually:
.. Open the monitor that contains the test that you want to base a new test on.
.. Download the test by clicking the download icon.
.. Edit the test manually, but do not change the name of the project folder. For example, if the `.zip` file is named `612dbc11-a043-4b8b-b76e-7d51f84723c7_test_1.0.0.zip`, the project folder has the same name, without the file extension, of course. Keep the name of the project folder as is.
.. In Anypoint Platform, upload the project folder.

+
Anypoint Platform adds the edited test as a new version of the original test in the *Tests* section for the same monitor.

== Result
Previous versions are listed in the *Tests* section for the monitor, so that you can still view the data that is associated with them. You can create versions that are based on any previous version.

A version number is automatically assigned to the new version.

Schedules that ran the base version now run only the new version. The base version is no longer scheduled to run. If you want to run any of the previous versions, you can create new schedules for them. For example, suppose that a monitor contains one test that is versioned 1.0.0. You create a version that is based on 1.0.0. As a result, the schedules that ran 1.0.0 now run only 1.0.1.

== See also

* xref:bat-bdd-reference.adoc[BDD Test Writing Language Reference]
