= API Functional Monitoring in Anypoint Monitoring
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can monitor APIs in the *Functional Monitoring* section of Anypoint Monitoring, which you can access from the home page of Anypoint Platform.

To monitor an API means to check its responses to requests that are sent to the resources at its endpoints. The *Functional Monitoring* section contains tools for creating a monitor and for editing monitors. Also, if you've created a monitor by writing a test suite in the Behavior Driven Development (BDD) test-writing language, you can upload that monitor.

A new monitor consists of a test and a schedule for that test. When you create a monitor, you specify for the test that the monitor includes:

* The endpoints that you want to test
* Optional assertions to test at the endpoints (for example, you might expect a 200 status code)
* Optional HTTP request headers to include when pinging the endpoints
* Optional reporting tools which you want the results of the test sent to (such as SumoLogic or Slack)

For the schedule that the monitor runs the test according to, you specify:

* The location from which to run the test.
+
Locations can be public or private. For details, see xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs] and xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs].
* The interval of time to wait between executions of the test.

When you create the monitor, you specify the endpoints that you want to test. For the schedule, you specify the location in which to run the test, and the interval at which to run the test.


== See also

* xref:afm-create-monitor.adoc[Create a Monitor]
* xref:afm-upload-monitor.adoc[Upload a Monitor]
