= Using Secrets to Mask Sensitive Information in Monitors

You can mask sensitive information in monitors that you run in a private location. 

To do so, do the following:

. <<configure-secret,Configure a shared secret>> in Secrets Manager for the information you want to mask. 
. <<add-secret-to-monitor,Modify your monitor>> to use the information from Secrets Manager.
. <<grant-access-to-secret,Grant the monitor permission>> to access the secret, which creates an alias for the secret.
. To deploy your changes, <<deploy-updated-monitor,upload the modified monitor>> to Functional Monitoring.

To mask the header information, the following files must be modified:

* `main.dwl`: Contains the test code to which the information from Secrets Manager must be added.
* `bat.yaml`: Contains configuration information that is modified later by BAT CLI when you grant your monitor access to the secrets. 

// Procedure to add secrets in Secret Manager

include::_partials/afm-task-config-secrets.adoc[tag=config-in-secrets-mgr,leveloffset=+1]

[[add-secret-to-monitor]]
== Add the Secret to Your Monitor

Modify your monitor to use the information you configured in Secrets Manager.

To add the secret to a monitor:

. Create or download a monitor. See xref:afm-create-monitor.adoc[Creating Monitors] or xref:afm-download-test.adoc[Downloading Monitors].
. Modify the `main.dwl` file to replace the sensitive information with the client ID and client secret you configured in Anypoint Secrets manager. In the following example, the sensitive information in headers are masked. 
+
----
import * from bat::BDD
import * from bat::Assertions

var cliId = secret('clientId-alias') default 'Client Not Found'
var cliSecret = secret('clientSecret-alias') default 'Secret Not Found'

suite("HTTP Monitor") in [
  it should "Assert endpoint: http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok"" in [
    GET `http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok` with {
      "headers": {
        "client_id": cliId,
        "client_secret": cliSecret
      }
    } assert [
        $.response.status mustEqual 200
    ]
  ]
] 
----

After you have modified the monitor's `main.dwl` file to add the secret information to the code, grant the monitor access to the secrets you configured in Secrets Manager. See <<grant-access-to-secret>>.

// Procedure to grant the monitor access to the secret

include::_partials/afm-task-config-secrets.adoc[tag=grant-access-to-secret,leveloffset=+1]

// Procedure to upload the monitor to deploy the changes

include::_partials/afm-task-config-secrets.adoc[tag=deploy-monitor,leveloffset=+1]