= Masking Headers in Monitors

You can mask, or hide, the authentication headers in a monitor that you run in a private location. 

To do so, do the following:

. <<configure-secret,Create a shared secret>> in Secrets Manager for the information you want to mask. 
. <<add-secret-to-monitor,Modify your monitor>> to use the information from Secrets Manager.
. <<grant-access-to-secret,Grant the monitor permission>> to access the secret, which creates an alias for the secret.
. <<deploy-updated-monitor,Upload the modified monitor>> to Functional Monitoring.

To mask the header information, the following files must be modified:

* `main.dwl`: Contains the test code to which the information from Secrets Manager must be added.
* `bat.yaml`: Contains configuration information that is modified later by BAT CLI when you grant your monitor access to the secrets. 
* `exchange.json`: Contains the versioning information. You might need to update this when uploading the monitor again.

// Procedure to add secrets in Secret Manager

include::_partials/afm-task-config-secrets.adoc[tag=config-in-secrets-mgr,leveloffset=+1]

[[add-secret-to-monitor]]
== Add the Secret to Your Monitor's Header

To add the secret to your monitor's header:

. Download your monitor. See xref:afm-download-test.adoc#download-a-monitor[Download a Monitor].
. Modify the `main.dwl` file as shown in the following example:
+
----
import * from bat::BDD
import * from bat::Assertions

var cliId = secret('clientId-alias') default 'Client Not Found'
var cliSecret = secret('clientSecret-alias') default 'Secret Not Found'

suite("HTTP Monitor") in [
  it should "Assert endpoint: http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok"" in [
    GET `http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok` with {
      "headers": {
        "client_id": cliId,
        "client_secret": cliSecret
      }
    } assert [
        $.response.status mustEqual 200
    ]
  ]
] 
----

After you have modified the monitor's `main.dwl` file to add the secret information to the code, grant the monitor access to the secrets you configured in Secrets Manager. See <<grant-access-to-secret>>.

// Procedure to grant the monitor access to the secret

include::_partials/afm-task-config-secrets.adoc[tag=grant-access-to-secret,leveloffset=+1]

// Procedure to upload the monitor to deploy the changes

include::_partials/afm-task-config-secrets.adoc[tag=deploy-monitor,leveloffset=+1]