= Monitoring Public APIs Versus Monitoring Private Ones

Tests are run by instances of Mule, and these instances are called _workers_. A worker can run in one of two types of location:

* One of the 12 different _worker clouds_, each corresponding to a geographic region. The complete list of regions is listed in the "Global Worker Clouds" section of the topic xref:runtime-manager::cloudhub-architecture.adoc[About CloudHub Architecture].

Whether you can monitor the endpoints of a public API or of an API that is in a private network depends on the type of location that you choose to run a test in. A _location_ in API Functional Monitoring is the place you specify that the test should be run. You select a location when you create a schedule for a version of a test.

== Types of Location

There are two types of location:

* Public locations are standard locations that are provided by CloudHub for testing endpoints of APIs that are publicly accessible.
+
These locations might run schedules for many MuleSoft customers; therefore, the load that any one customer can place on CloudHub is limited. You have a limited number of schedules that you can create; must pay more for the allocation of more schedules.
+
Examples of public locations:
+
** us-east-1
** us-east-2

Private location:: You create private locations. These are Mule workers that you allocate, that run in an Anypoint Platform environment, and that act as proxies to allow the testing of endpoints of APIs that are accessible only within private networks. You can to create as many schedules as your allotment of vCores can accommodate. Every private location consumes 0.2 vCores.
+
When you create a private location, you can give it any name you like.

== Select a Public Location When You Create a Monitor in Anypoint Monitoring

When you create a monitor, you create version 1.0.0 of the test that the monitor runs and the schedule for running the test. The fields under the heading *Execution Location* are for configuring the schedule. In the *Location* field, click the arrow and, in the menu that appears, select one of the options under the heading *Public Locations*.


== Select a Public Location When You Modify or Create a Schedule in Anypoint Monitoring

In an existing monitor, you can modify or add a schedule in the *Schedules* section.

* To the right of schedule listed in the table in this section, click the three dots and select *Modify* to open the Modify Schedule dialog.
* Click the *Add Schedule* button to open the Add Schedule dialog.

In either dialog, click the arrow in the *Location* field and select one of the options under the heading *Public Locations*.


== Specify a Public Location When You Create a Monitor by Using the BAT CLI



== Select or Create a Private Location When You Create a Monitor in Anypoint Monitoring


== Select or Create a Private Location When You Create a Schedule in Anypoint Monitoring


== Specify a Private Location When You Create a Monitor by Using the BAT CLI
