= Add a Schedule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can add schedules to a monitor if you need each schedule to run the monitor from a different location, or if you uploaded a monitor that includes multiple configuration files and you want each schedule to use a different configuration.

You can add a schedule to an existing monitor if either of the following two conditions is true:

* You plan to run the monitor's test from a public location and the allocation of schedules for your organization in Anypoint Platform is not exhausted.
* You plan to run the monitor's test from a private location.


== Procedure

. In the list of monitors, select the monitor to which you want to add a schedule.
. On the details page for the monitor, follow one of these steps:
+
*  If at least one schedule exists, click the three dots in the entry for a schedule and then select *Add Schedule*.
+
* If no schedule exists, click *Add Schedule*.
. In the *Add Schedule* dialog, specify this information:
+
* The location to run the test from
* The frequency at which to run the test
. Click *Add Schedule*.



== See Also

* The section "The `config` Folder" in * xref:bat-example-test-suite.adoc[Example of a Test Suite]
* xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs]
* xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs and Mixes of Public and Private APIs]
