= Create a Private Location
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can create a private location as part of three tasks:

* When you create a monitor
* When you add a schedule to a monitor
* When you modify a schedule in a monitor

You can also create a private location independently of these three tasks. Then, when you create a monitor, add a schedule, or modify a schedule, you can simply select the private location. The following procedure explains the steps for this last method.

For information about what a private location is and why you might want to create one, see xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs].

== Before You Begin

Ensure that your organization in Anypoint Platform has a subscription to Anypoint Virtual Private Cloud.

== Procedure

To create a private location independently of any other task:

. Display the list of locations by clicking the *Locations* tab at the top of the screen.
. Click *Create Private Location*.
. Name the location.
+
The name can be up to 255 characters, and can include spaces and special characters.
. Select the environment in which to run the workers that are created to run tests in your monitors.
. Click *Create*.

== Result

The private location is added to the list of private locations. While API Functional Monitoring is registering the location, the status indicator for the location is yellow. After it is registered, if the environment in which the location was created is online, the location shows a green status indicator.

If the indicator is red, navigate to Runtime Manager and restart the environment. Then, check the logs for the environment to troubleshoot the problem that caused it to go offline.

== What to Do Next

You can now run tests from the private location, either by adding a schedule that uses the location or by modifying an existing schedule to use it.

== See Also

* xref:afm-public-versus-private.adoc[Differences in the Monitoring of Public and Private APIs]
* xref:afm-create-monitor.adoc[Create a Monitor]
* xref:afm-add-schedule.adoc[Add a Schedule]
* xref:afm-modify-schedule.adoc[Modify a Schedule]
