= Masking Headers in Monitors

You can mask, or hide, the authentication headers in a monitor that you run in a private location. 

To do so, do the following:

. <<configure-secret,Create a shared secret>> in Secrets Manager for the information you want to mask. 
. <<add-secret-to-monitor,Modify your monitor>> to use the information from Secrets Manager.
. <<grant-access-to-secret,Grant the monitor permission>> to access the secret, which creates an alias for the secret.
. <<deploy-updated-monitor,Upload the modified monitor>> to Functional Monitoring.

To mask the header information, the following files must be modified:

* `main.dwl`: Contains the test code to which the information from Secrets Manager must be added.
* `bat.yaml`: Contains configuration information that is modified later by BAT CLI when you grant your monitor access to the secrets. 
* `exchange.json`: Contains the versioning information. You might need to update this when uploading the monitor again.

[[configure-secret]]
== Configure a Secret in Anypoint Secret Manager

If you want to keep sensitive information, such as a license key, URL, or email ID, secret and you are running tests from a private location:

. In Anypoint Secrets Manager, create a shared secret as a symmetric key. If the sensitive information that you want to store as a shared secret is currently in plain text, then you must encode it in Base64 before you create the secret.

.. Open a secrets group or create a new one. The group must be created in the same environment that you are using in the BAT CLI. To find out which environment you are currently using in the BAT CLI, run the command `bat whoami`. In the output, there is the ID for the environment. Run the command `bat environment ls` to list the environments that you have access to. Match the ID from the `bat whoami` command with one of the environments listed. If you need to switch to the environment that your secrets group is in, run the command `bat environment switch name`, where `name` is the name of the environment.

.. Select *Shared Secret*.
.. In the *Type* field, select *Symmetric Key*.
.. In the *Key* field, paste the sensitive information encoded as a Base64 string.
.. Paste the Base64 string into the *Confirm Key* field.

. Copy the name of the new shared secret.

[[add-secret-to-monitor]]
== Add the Secret to Your Monitor

To add the secret to your monitor:

. Download your monitor. See xref:afm-download-test.adoc#download-a-monitor[Download a Monitor].
. Modify the `main.dwl` file as shown in the following example:
+
----
import * from bat::BDD
import * from bat::Assertions

var cliId = secret('clientId-alias') default 'Client Not Found'
var cliSecret = secret('clientSecret-alias') default 'Secret Not Found'

suite("HTTP Monitor") in [
  it should "Assert endpoint: http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok"" in [
    GET `http://status-coder.ir-e1.cloudhub.io/status?code=200&reason=Ok` with {
      "headers": {
        "client_id": cliId,
        "client_secret": cliSecret
      }
    } assert [
        $.response.status mustEqual 200
    ]
  ]
] 
----


[[grant-access-to-secret]]
== Grant Your Monitor Access to the Secret

After you have modified the monitor's `main.dwl` file to add the secret information to the code, you grant the monitor access to the secrets you configured in Secrets Manager.

To grant your monitor access to the secret:

. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret. When you run this command, the BAT CLI creates a section named `secrets` in your test suite's `bat.yaml` file, if the section does not already exist. In that section, the BAT CLI adds these indented lines:
+
----
alias:
 secretId: "secret-ID"
----
+
* `alias`: This is the alias that you specified in the `bat grant` command.
* `secret-ID`: This is the ID of the secret within Anypoint Secrets Manager. This ID does not appear in ASM, so there is no way for someone looking in your `bat.yaml` file to associate the ID with any particular secret. The BAT CLI uses this ID to look up the secret that you associated with the alias.


[[deploy-updated-monitor]]
== Deploy the Updated Monitor

Upload your updated monitor as documented in xref:afm-upload-monitor.adoc#upload-a-monitor[Upload a Monitor].