= Adding Schedules

:imagesdir: ../assets/images

You can add a schedule to an existing monitor if either of the following two conditions is true:

* You plan to run the test associated with the schedule in a public location, and the allocation of schedules for your Anypoint Platform organization is not exhausted.
* You plan to run the test associated with the schedule in a private location.

== Before You Begin

Ensure that you have the following permission set in Access Management:

* *Exchange > Exchange Administrator* or *Exchange > Exchange Contributor*

An Anypoint Platform administrator for your organization grants permission. See xref:access-management::managing-permissions.adoc[Manage Permissions].

== Add a Schedule

. Select the monitor in which you want to add a schedule.
. Click *Add Schedule* from the *Schedules* table.
. In the *Add Schedule* dialog box, select the following:
+
* The location in which to run the test
* The monitor schedule interval and its required information:
+
|===
|Interval |Required Information |Definition

|Hourly
|The minute
|The minute at which the test begins, starting 60 minutes after you create the schedule

|Daily
|The time of each day
|The time each day (hour and minutes) at which the test begins

|Weekly
|Day of the week and time of day 
|The day of the week and the time of that day that initiates the test

|Monthly
|Day of the month and time of day 
|The day of the month and the time of that day that initiates the test

|Advanced
|Cron
|The cron expression for the frequency of the test. 

|===

. Set *Configuration*.

. Click *Add*.
+
The countdown to the first run of the selected test begins.

[NOTE]
====
Specified test times correspond with your time zone.
====

// Explanation and table with schedule interval options by location type

include::_partials/afm-ref-schedule-interval.adoc[leveloffset=+1]

== Scheduling Long-Running Tests

Tests for a monitor that are run in public locations silently fail when the run time exceeds 120 seconds. If you need longer tests, the best solution is to use a private location, because you can run tests of long duration in private locations. 

If you want to run longer-running tests in a public location, you can:

. Download the monitor and split the tests across multiple monitors using the BAT CLI. 
. Run and time each test to ensure their running times are under 120 seconds. 
. Upload the tests as separate monitors to run in the web UI or simply run them through BAT CLI. 

== See Also

* xref:afm-public-versus-private.adoc[Differences in the Monitoring of Public and Private APIs]
* xref:access-management::managing-permissions.adoc[Manage Permissions]