= Create a Monitor When Evaluating API Functional Monitoring

When you are evaluating API Functional Monitoring, you can create a monitor that tests one or more endpoints that are in one or more public APIs. You can run up to five such monitors concurrently.

For details, see xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs]

== Before You Begin

* Ensure that your user ID has the "Anypoint Monitoring User" permission.
+
An administrator for your organization can use Anypoint Access Management to grant you this permission.
* Determine which endpoints you want to test and the HTTP methods that you want to test them with.
* Decide which return codes the methods must return.
* Decide the frequency at which you would like the monitor to test the endpoints.
+
The shortest interval is every fifteen minutes. You can also choose to run the monitor hourly, daily, weekly, or monthly. The schedule begins immediately after you create the monitor. You can schedule another monitor later for the same test suite that is more detailed, if you prefer. You can also modify the schedule after you create the monitor, if you want to specify any of these options:
** Set an hourly schedule to start at a certain number of minutes after the hour begins.
** Set a daily, weekly, or monthly schedule to start at a certain time of day.
* Decide whether you would like the request messages to include additional header information.
* If you would like to send reports to one or more of these reporting tools, obtain the information that is required by the reporting tools:
+
|===
|Reporting Tool |Required Information

|NewRelic
|License Key

|PagerDuty
|RoutingKey

|Slack
|Webhook

|SumoLogic
|Endpoint

|Email
|Email address
|===

== Procedure
To create a monitor:

. In the *Functional Monitoring* section of Anypoint Monitoring, click *Create*.
. Specify a name and a short description for the monitor.
. Fill in the fields with the information that you have gathered.
. Click *Create*.
