= Create a Monitor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You create monitors via the Functional Monitoring UI or by uploading test suites written in BAT, a Behavior Driven Development (BDD) language. Both methods enable you to create tests against one or more endpoints, and to create test schedules that run at specified intervals. 

This procedure describes creating monitors via the Functional Monitoring UI.

== Before You Begin

* Ensure that your user ID has the Anypoint Monitoring User permission and that it has been assigned the Exchange Administrators role. An administrator for your organization can grant this permission in Anypoint Access Management.
* Determine which endpoints to test and the REST methods that test them.
* Determine the expected return status codes.
* Determine the test interval.
+
The shortest interval is fifteen minutes. Monitors can also run hourly, daily, weekly, or monthly. The schedule begins immediately after creating the monitor, and you can modify the schedule after the monitor has been created. For example:

** Set an hourly schedule to start at a certain number of minutes after the hour begins.
** Set a daily, weekly, or monthly schedule to start at a certain time of day.

* Determine the location in which to execute the monitor.
+
For details, see xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs] and xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs].
* Determine if the requests should include additional headers.
* For reporting, obtain one of the following pieces of information:
+
|===
|Reporting Tool |Required Information

|PagerDuty
|RoutingKey

|Slack
|Webhook

|SumoLogic
|Endpoint

|Email
|Email address
|===


== Procedure
To create a monitor:

. Click *Create Monitor* in the *Functional Monitoring* section of Anypoint Monitoring.
. Specify a monitor name.
. Populate the fields with the information gathered in "Before you Begin".
. Click *Create Monitor*.

== Result

The detail view includes the following monitor actions:

* Run 
* View history
* Edit
* Download
* Delete

Beneath the monitor name is a field showing the duration of the most recent run. A graph beneath the duration displays the average time each activity took, separated by day. Beside the graph, a list of the last five executions is displayed. 

In the next line, you can see a table with the current schedules associated with the test. Finally, beneath the table, the last execution is shown.

[IMPORTANT]
====
Tests silently fail when they take more than 120 seconds to run. As a workaround, you can split a long-running test into multiple tests. Download the monitor, split the test across multiple monitors in the BAT CLI, run and time each test to be sure that it is under 120 seconds, and then upload the monitors.

If you do not want to split a long-running test, download the monitor and run it from the BAT CLI.
====

== What to do next

From Monitor Detail, you can add additional schedules and delete schedules that you no longer want to run. You can also disable schedules, if you want to pause them, and then enable them again.

After the monitor runs, the last execution is shown in the inferior part of the screen here we can see listed:

* Time elapsed since monitor started running
* Whether all endpoints returned the expected codes, as indicated by *PASSED* or *FAILED* in the status line
* Each endpoint asserted with its HTTP method
* Assertions expected from each endpoint

To see statistics and other information about the monitor, the *Last Executions* table is displayed. Because you have only one test in the monitor that you just created, the statistics and information in this section apply to the test only. When clicking in one of the executions, extra information is shown.

If you want to delete the monitor, click the three dots besides the monitor name and then choose Delete monitor.

== See Also

 * xref:afm-edit-test.adoc[Edit a monitor]
 * xref:bat-top.adoc[API Functional Monitoring with the Blackbox Automated Testing (BAT) CLI]
