= Monitoring Public APIs Versus Monitoring Private Ones

Monitors (which contain both one or more versions of a test and one or more schedules) are run by instances of Mule Runtime, and these instances are called _workers_. Each worker runs a single monitor.

A worker normally runs in one of CloudHub's twelve different _worker clouds_. Each of these clouds corresponds to a geographic region. (The complete list of regions is listed in the "Global Worker Clouds" section of the topic xref:runtime-manager::cloudhub-architecture.adoc[About CloudHub Architecture].) When you create a monitor, add a schedule to a monitor, or modify a schedule, you can specify to run the worker in one of the regions that are available to you. For example, you might have access to the worker clouds `us-east-1` and `us-east-2`, and you could select one of these to run the worker in.

Workers that run in a worker cloud and that run the monitors you create with API Functional Monitoring (AFM) can run monitors that test only APIs that are publicly accessible. Such workers cannot access APIs that are in private networks.

Also, the number of workers that you can run at the same time in worker clouds is limited. For example, if your limit is five, the total number of workers that you can run simultaneously in worker clouds is five. If you run two in, say, `us-east-1` and three in `us-east-2`, you are still subject to the limit. You cannot run five in each worker cloud. If you reach the limit, you must contact your MuleSoft administrator about raising your maximum.

However, if you have a subscription to Anypoint Virtual Private Cloud (VPC), you can run workers in a virtual, private, and isolated network segment. These workers can access APIs in your private network. You can also run as many workers as your allotment of vCores allows. Each worker consumes 0.2 vCores.

== Public Locations and Private Locations

In AFM, a _public location_ is one of the twelve worker clouds. When you select one of these as part of creating a monitor or as part of adding or editing a schedule, you are specifying that the API that you want the monitor to test or the schedule to run a test against is a public API. In addition, you are specifying that you want to allocate a worker from the limited number of workers that you can allocate.

A _private location_ is a namespace in an instance of VPC that is configured to allow workers to access your private network. AFM can create workers within that namespace that can run tests against APIs that are accessible only within the network that VPC is configured for. You can create multiple private locations in a single VPC.

Before you can select a private location, you must create one, which involves specifying a name. For example, you might create a private location that you name `myLocation`. When you choose to run a monitor in `myLocation`, AFM allocates a worker in Anypoint Virtual Cloud in the `myLocation` namespace.

== Select a Public location When You Create a Monitor in Anypoint Monitoring

When you create a monitor, you create version 1.0.0 of the test that the monitor runs and the schedule for running the test. The fields under the heading *Execution location* are for configuring the schedule. In the *location* field, click the arrow and, in the menu that appears, select one of the options under the heading *Public locations*.


== Select a Public location When You Modify or Create a Schedule in Anypoint Monitoring

In an existing monitor, you can modify or add a schedule in the *Schedules* section.

* To the right of schedule listed in the table in this section, click the three dots and select *Modify* to open the Modify Schedule dialog.
* Click the *Add Schedule* button to open the Add Schedule dialog.

In either dialog, click the arrow in the *location* field and select one of the options under the heading *Public locations*.


== Specify a Public location When You Create a Monitor by Using the BAT CLI



== Select or Create a Private location When You Create a Monitor in Anypoint Monitoring


== Select or Create a Private location When You Create a Schedule in Anypoint Monitoring


== Specify a Private location When You Create a Monitor by Using the BAT CLI
