= Creating Monitors

You create monitors via the Functional Monitoring UI or by uploading test suites written in BAT, a Behavior Driven Development (BDD) language. Both methods enable you to create tests against one or more endpoints, and to create test schedules that run at specified intervals. 

This procedure describes creating monitors via the Functional Monitoring UI.

[[before-you-begin]]
== Before You Begin

Ensure that you have the following permissions set in Access Management:

* *Anypoint Monitoring > Viewer* or *Anypoint Monitoring > Administrator* 
+
and
+
* *Exchange > Exchange Administrator* or *Exchange > Exchange Contributor*

An Anypoint Platform administrator for your organization grants permission. See xref:access-management::managing-permissions.adoc[Manage Permissions].

[[create-a-monitor]]
== Create a Monitor

To create a monitor:

. Click *Create Monitor* in the *Functional Monitoring* section of Anypoint Monitoring.
. Under *Step 1 - Setup the monitor*:
.. Specify a monitor name.
.. Select a testing location. 
.. Set the monitoring schedule. 
. Click the *Step 2 - Select endpoints* tab and enter the following for each endpoint: 
.. By default, the monitor validates self-signed certifications for each endpoint, so *Validate SSL Certificate* is toggled on. To allow unsafe self-signed certifications for an endpoint, toggle *Validate SSL Certificate* off.
.. Select the method and enter the endpoint URL.
.. Search for, select, or configure custom headers and insert a value for each header. 
.. For POST, PUT, or PATCH endpoints, insert the body content.
.. Configure assertions' status code, response body, and response header.   
+
.. Preview the test by clicking *Run now* under *Preview the result of your monitor*.
+
. Click the *Step 3 - Set notifications* tab.
+
* Optionally select notifiers from the list of integrating reporting tools and enter the required information in the value field for each selected notifier:
+
|===
|Reporting Tool |Required Information

|New Relic
|License Key

|PagerDuty
|RoutingKey

|Slack
|Webhook

|SumoLogic
|Endpoint

|Email
|Email address
|===
+
To hide the required information in the monitor files, see xref:bat-reporting-task[Configuring and Viewing Reports]. 
+
. Click *Create Monitor*.

== See Also

* xref:bat-top.adoc[API Functional Monitoring with the Blackbox Automated Testing (BAT) CLI]
* xref:access-management::managing-permissions.adoc[Managing  Permissions]
* xref:afm-modify-monitor.adoc[Modifying Monitors]
* xref:afm-add-schedule.adoc[Adding Schedules]
* xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs]
* xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs]