= Creating Private Locations

:imagesdir: ../assets/images
 
// Definition of Private Locations

include::_partials/afm-concepts.adoc[tag=afm-private-locations,leveloffset=+2]

You can create a private location when you:

* xref:afm-create-monitor.adoc[Create a monitor]
* xref:afm-add-schedule.adoc[Add a schedule] to a monitor
* xref:afm-modify-schedule.adoc[Modify a schedule] in a monitor

This procedure explains how to create a private location when you modify a schedule.

For information about private locations and their uses, see xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs].

== Before You Begin

* Ensure that your Anypoint Platform organization has a subscription to Anypoint Virtual Private Cloud.

* Ensure that you have the following permission set in Access Management:

** *Runtime Manager > Create Applications*

An Anypoint Platform administrator for your organization grants permission. See xref:access-management::managing-permissions.adoc[Manage Permissions].

== Create a Private Location

To create a private location:

. When creating a test or schedule, click the field under *Select location* and select *Create new location*.
. Name the location.
+
The name can be up to 255 characters, and can include spaces and special characters.
. Select the environment for the tests.
. Complete the creation of the of test or schedule.
+
While API Functional Monitoring is registering the private location, the status indicator is yellow. After the location is successfully registered, the status indicator is green.
+
. If the status indicator is red: 
.. Navigate to Runtime Manager and restart the application/worker cloudhub application. 
.. Check the logs for the application/worker cloudhub application to troubleshoot the issue.

== What to Do Next

You can now run tests from the private location, either by adding a schedule that uses the location or by modifying an existing schedule to use it.

== See Also

* xref:afm-create-monitor.adoc[Creating Monitors]
* xref:afm-add-schedule.adoc[Adding Schedules]
* xref:afm-modify-schedule.adoc[Modifying Schedules]
* xref:access-management::managing-permissions.adoc[Managing Permissions]
* xref:cloudhub::virtual-private-cloud.adoc[Virtual Private Cloud]
