= Create a New Test from an Existing One
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You cannot edit a test that exists for a monitor, but you can create a new test that is based on one. In the new test, you can change, remove, or add assertions, headers, endpoints, and reporters.

You can create a new test only if the test that it is based on has not been customized to include features that the *Create a Monitor from Scratch* page does not support. (It is possible to customize a test by downloading it, editing it manually, and then uploading it.) Tests created manually and then uploaded also are not editable if they contain features that the *Create a Monitor from Scratch* page does not support.

== Procedure

. Open the monitor that includes the test that you want to base a new test on.
. Click the *Tests* tab.
. Find the test and click the pencil icon directly beneath it.
. In the *Modify Existing Monitor* page, make your changes to the test.

== Result

After you click *Update*, the new test is listed in the *Tests* section for the monitor. Previous tests are still listed, so that you can still view the data that is associated with them.

A version number is automatically assigned to the new test. The number is based on the version number of the test that it is based on. For example, suppose that a monitor contains one test and the version number of the test is 1.0.0. If you create a new test from this one, the number assigned to the new test is 1.0.1. Next, if you create a new test that is based on either test 1.0.0 or 1.0.1, the new test is assigned the number 1.0.2.

Schedules that ran the base test now run only the new test. The base test is no longer scheduled to run. If you want to run any of the previous tests, you can create new schedules for them. For example, suppose that a monitor contains one test that is versioned 1.0.0. You create a new test that is based on this test. As a result, the schedules that ran 1.0.0 now run only 1.0.1.
