= Add a Schedule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can add schedules to a monitor on more than one schedule if you need to run the monitor's test at irregular intervals. For example, you might want to run the test three times daily: 8 in the morning, noon, and 8 in the evening. To do so, you would run the test on three separate schedules.

You can add a schedule to an existing monitor if either of the following two conditions is true:

* You plan to run the monitor's test from a public location and the allocation of schedules for your organization in Anypoint Platform is not exhausted.
* You plan to run the monitor's test from a private location.


== Procedure

. In the list of monitors, select the monitor to which you want to add a schedule.
. ???
. Select *Add Schedule*.
. In the Add Schedule dialog, specify this information:
+
* The location to run the test from
* The frequency at which to run the test
. Click *Add Schedule*.


== See Also

* xref:afm-monitoring-public-apis.adoc[Monitoring the Endpoints of Public APIs]
* xref:afm-monitoring-private-apis.adoc[Monitoring the Endpoints of Private APIs and Mixes of Both Public and Private APIs]
