= Delete a Schedule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You might want to delete a schedule for any of the following reasons:

* You are finished testing endpoints of a public API and you want to free resources for testing the endpoints of a different public API.
* You are finished testing endpoints of a private API.
* You have more than one schedule running the same test and you no longer need one of the schedules.

[IMPORTANT]
====
Be sure that you want to delete a schedule. API Functional Monitoring does not give you a chance to confirm that you want to delete it.
====

== Procedure

To delete a schedule, follow either of these procedures:

* If you know which monitor uses the schedule, follow these steps:
. In the list of your monitors, select the monitor in which you want to delete a schedule.
. Locate the schedule in the list.
. Click the three dots to the right of the list entry for the schedule.
. Select *Delete Schedule*.

* If you know which location the schedule uses, follow these steps:
. Above the list of your monitors, click the *Manage Locations*.
. Locate the location and expand its entry.
. Locate the schedule and click the three dots on the right side of its entry.
. Select *Delete Schedule*.

== Result

If the schedule that you deleted was the only schedule that was using a private location, you can now delete that private location, if you want to do so.
