= Start a New Test Suite
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Starting a new test suite for testing API endpoints involves only a few steps to create and populate with initial lines a file named `bat.yaml`. This file explains the structure of your test suite to the BAT CLI.

== To Start a New Test Suite
. Create a directory in your computer's filesystem.
. Change to the new directory.
. Create a file named `bat.yaml`.
. Open the file for editing.
. Add these five lines:
+
[source,yaml]
----
suite:
  name: "name_of_suite_of_tests"

files:

----
+
name_of_suite_of_tests:: Specify the name that you want to give the suite of tests that you plan to write.
. Save the file.
. Create a folder in your directory in which to create tests. You can give the folder any name.
. Create a folder named `config`. In this folder, you create configuration files to use for your tests. Configuration files contain information that the BAT CLI needs to connect to the systems where the APIs that you want to test are located.

== What to Do Next

Now, you can start writing tests.

== See Also

* xref:bat-example-test-suite.adoc[Example of a Test Suite]
