= API Functional Monitoring with the Blackbox Automated Testing (BAT) CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: bat-workflow-test.adoc

You can use API Functional Monitoring to run a test or suite of tests on an API. API Functional Monitoring is based on Blackbox Automated Testing (BAT).

Using API Functional Monitoring, you can automate testing and get test reports. You can test before pushing code into your repository and before deploying to production. Tests can verify API functionality and validate results the API generates. You can monitor APIs at each stage of the software development life cycle and in production.

The prerequisites for performing API functional testing and scheduling are:

* Deployed API
+
You can deploy an API on Anypoint Platform or your own server.
* Installation of BAT.
* A YAML configuration file (manifest file).
* At least one test file.
+
** You write files in Behavior Driven Development (BDD) syntax using a code or text editor, such as IntelliJ.
** You save the files using the `.dwl` extension for processing by DataWeave.

Additional prerequisites for monitoring scheduled tests in the cloud are:

* An account on Anypoint Platform.
* A reporting tool supported by BAT.

== BAT Playground

The BAT playground is a web application you can use to familiarize yourself with Behavior Driven Development (BDD) syntax. In the playground, you can run playground-provided tests or your own.

== See Also

* xref:bat-install-task.adoc[Install BAT]
* xref:bat-bdd-reference.adoc[BDD Test Writing Language Reference]
