= API Functional Monitoring with the Blackbox Automated Testing (BAT) CLI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: bat-workflow-test.adoc

You can use API Functional Monitoring to run a test or suite of tests on one or more APIs. API Functional Monitoring is based on Blackbox Automated Testing (BAT).

Using API Functional Monitoring, you can automate testing and get test reports. You can test before pushing code into your repository and before deploying to production. Tests can verify API functionality and validate results the API generates. You can monitor APIs at each stage of the software development life cycle and in production.

The prerequisites for testing and scheduling are:

* One or more deployed APIs
* Installation of BAT.
* A directory that contains a test suite.
* At least one test file in that directory.
+
You write tests in Behavior Driven Development (BDD) syntax using a code or text editor, such as IntelliJ. Test files must use the `.dwl` extension for processing by DataWeave.

An additional prerequisite, this one for monitoring scheduled tests in the cloud, is an account on Anypoint Platform.


== See Also

* xref:bat-install-task.adoc[Install BAT]
* xref:bat-bdd-reference.adoc[BDD Test Writing Language Reference]
