= Run a Test Suite

Using the BAT CLI, you can execute one test at a time or all tests listed in the `bat.yaml` file for a test suite.

== To Run Tests

* To run all of the tests that are listed in the `bat.yaml` file for a test suite, run the `bat` command at the root level in your test-suite directory. Your `bat.yaml` file for the test suite must also be at the root level in this directory.

* To run a single test that is listed in the `bat.yaml` file for a test suite, run the command `bat ./folder/file.dwl` at the root level in your test-suite directory:
+
`folder`:: Specify the path to the test file.
+
`file.dwl`:: Specify the name of the test file.
+
Your `bat.yaml` file for the test suite must also be at the root level in the test-suite directory.

== What to Do Next

By default in the example test suite that you can generate with the `bat init` command, BAT generates an HTML report about the test results. The configuration of this report is in the `reporters` section on the `bat.yaml` file.
+
.The default configuration of the HTML report
[source,yaml]
----
reporters:
    - type: HTML
      outFile: /tmp/HTML.html
----

However, you can receive reports of test failures from several supported applications, not just in an HTMl file. See xref:bat-reporting-task.adoc[Configuring and Viewing Reports].