= Getting Started Writing Tests
:page-aliases: bat-playground-task.adoc

A test suite is composed of the following elements:

* A directory that contains a main file named `bat.yaml` that describes the structure of your test suite
* A `config` folder that contains files in which you specify variables
* One or more folders in which you write tests

Tests are written in the BDD Test-Writing syntax and use the `.dwl` file extension.

[[before-you-begin]]
== Before You Begin

Before you can write and run tests, you must have access to an Anypoint Platform account. 

[[test-examples]]
== Use Examples to Learn the Basics
Learn the basics of writing tests using the provided examples. 

To select examples:

. In the *Create Monitor* or *Edit Monitor* page, click *Switch to code editor*. 
. In the *Load Test Examples* selector above the code editor, select an example. Examples include:
+
** Test an expected status code
** Validate multiple assertions
** Set and reuse variables
** Iterate
** Extract functions
** Assert with regex
** Repeat n times
+
The code in the code editor automatically changes to show the selected example code.

See xref:bat-bdd-reference.adoc[] to understand the syntax and write your own tests.

[[validate-tests]]
== Validate Tests
To validate a test when creating or modifying a monitor, switch to the code editor view and then click *Validate Test*.

== See Also

* https://deckofcardsapi.com/[The website for the Deck of Cards API]
* xref:bat-bdd-reference.adoc[]
* xref:afm-create-monitor.adoc[]
* xref:afm-modify-monitor.adoc[]