= Installing BAT

The Blackbox Automated Testing (BAT) CLI wrapper is a command line wrapper that you install to execute API tests.

== Prerequisite for Linux and MacOS Systems

Before installing the BAT CLI, ensure that AdoptOpenJDK's OpenJDK 8 is installed on your system.

== Prerequisites for Windows 10 Systems

. Install Windows Subsystem for Linux (WSL)
+
The instructions are at https://docs.microsoft.com/en-us/windows/wsl/install-win10.
. Install Java 8, curl, and the application "unzip" into the Linux distribution that you installed in your WSL.
. Add the `bat` executable to your `PATH` environment variable:
.. Open the `~/.bashrc` file (if you are using `bash`) or the `~/.zshrc` file (if you are using `zsh`) for editing. For example, to use the `vi` editor, enter either of these commands:
+
`vi ~/.bashrc`
+
`vi ~/.zshrc`
.. Add the following line to the end of the file and then save the file:
+
`export PATH=$PATH:~/.bat/bat/bin`

[[to-install-bat]]
== Install BAT

You can install BAT CLI on Linux or Windows OS. 

=== Mac OS

For the standard Mac OS use the instructions for Linux. To run BAT CLI in a Windows partition on a Mac, use the instructions for Windows. 

=== Linux 

. Ensure that the user under which you are installing has write and execute permissions for the directory into which you plan to install BAT CLI.
+
. Run the following command to install BAT CLI:
+
`curl -o- 'https://s3.amazonaws.com/bat-wrapper/install.sh' | bash`
+
. Navigate to the directory under which you installed. 
+
TIP: You can add your installation directory path to your Linux shell file PATH so that you can run the commands from any directory. 
+
. Run the command `bat -version` to verify that the BAT CLI is installed.


=== Windows

Click https://repository-master.mulesoft.org/nexus/content/repositories/releases/com/mulesoft/bat/bat-wrapper/1.1.14/bat-wrapper-1.1.14.zip[here^] to automatically download the ZIP file of the BAT wrapper for Windows. After it downloads, unzip it to install it in your Windows environment.  

== What to Do Next

You can now start creating a test suite.

== See Also

* xref:bat-start-new-project.adoc[Starting a New Test Suite]
* xref:bat-command-reference.adoc[BAT Command Reference]
