= To Configure and View Test Reports
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can configure BAT for use with a number of reporting systems. For example:

* New Relic
* PagerDuty
* Slack
* SUMO
* Custom
* Local
* Email

Specify report generation in the `reporters` section of the bat.yaml file.

== New Relic

Using New Relic with API functional monitoring, you can determine the times of each test, detect performance loss, and schedule alerts.

New Relic has a plugin configured for BAT that can capture the metrics from test suites. To use the plugin to capture metrics, you need to configure your bat.yaml file by adding the following information:

* An output directory
* Your NEW_RELIC_LICENSE_KEY

=== To Configure Reporting

. Obtain your New Relic license key.
+
* Go to the New Relic Account Settings.
* Copy your license key from the right sidebar under Account Summary.
. In your `bat.yaml` file, create the `reporters` section, if one doesn't already exist in the file. On a blank line, type `reporters:`.
. If you want to keep your license key secret and you are running tests from a private location:
.. In Anypoint Secrets Manager, create a shared secret as a symmetric key that uses Base64 encoding.
... Open a secrets group or create a new one.
... Select Shared Secret on the left side of the screen.
... In the *Type* field, select *Symmetric Key*.
... In the *Key* field, paste your license encoded as a Base64 string.
... Paste the same Base64 string into the *Confirm Key* field.
.. Copy the name of the new shared secret.
.. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret.
.. In your `bat.yaml` file, add New Relic as a reporter by adding these indented lines to the `reporters` section:
+
[source,yaml]
----
 - type: NewRelic
   outFile: filename.json
   options:
     NEW_RELIC_LICENSE_KEY: <alias_of_the_shared_secret>
----
+
filename.json:: Specify a name for the output file to create.
alias_of_the_shared_secret:: Specify the alias that you used for the secret for the license key when you ran the `bat grant` command. The alias must be between carets.
. If you do not want to keep your license key secret, in your `bat.yaml` file add New Relic as a reporter by adding these indented lines to the `reporters` section:
+
[source,yaml]
----
 - type: NewRelic
   outFile: filename.json
   options:
     NEW_RELIC_LICENSE_KEY: "license_key"
----
+
filename.json:: Specify a name for the output file to create.
license_key:: Specify the license key.

=== What to Do Next

After a test runs, go to New Relic and click Plugins. The BAT plugin information appears.

Click the test suite name to see the result of the test.

== PagerDuty

The integration of BAT with PagerDuty generates an incident when a test fails and triggers configured PagerDuty alerts. If a monitor always fails with the same error, BAT does not generate a new issue, but instead ignores these errors.

=== To Configure Reporting

. In PagerDuty, configure an integration:
.. Select *Configure* > *Services*.
.. Select the integration.
. Copy the service key.
. In your `bat.yaml` file, create the `reporters` section, if one doesn't already exist in the file. On a blank line, type `reporters:`.
. If you want to keep your service key secret and you are running tests from a private location:
.. In Anypoint Secrets Manager, create a shared secret as a symmetric key that uses Base64 encoding.
... Open a secrets group or create a new one.
... Select Shared Secret on the left side of the screen.
... In the *Type* field, select *Symmetric Key*.
... In the *Key* field, paste your service key encoded as a Base64 string.
... Paste the same Base64 string into the *Confirm Key* field.
.. Copy the name of the new shared secret.
.. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret.
.. In your `bat.yaml` file, add PagerDuty as a reporter by adding these indented lines to the `reporters` section:
+
[source,yaml]
----
 - type: PagerDuty
   outFile: filename.json
   options:
     SERVICE_KEY: <alias_of_the_shared_secret>
----
+
filename.json:: Specify a name for the output file to create.
alias_of_the_shared_secret:: Specify the alias that you used for the secret for the service key when you ran the `bat grant` command. The alias must be between carets.
. If you do not want to keep your license key secret, in your `bat.yaml` file add PagerDuty as a reporter by adding these indented lines to the `reporters` section:
+
[source,yaml]
----
 - type: PagerDuty
   outFile: filename.json
   options:
     SERVICE_KEY: "service_key"
----
+
filename.json:: Specify a name for the output file to create.
service_key:: Specify the service key.

=== What to Do Next

If a test fails, look in PagerDuty for the report.

== Slack

You can integrate BAT and Slack to send notifications to a Slack channel when tests fail. A notification provides the name of the suite in which the error occurs.

=== To Configure Failure Notifications

. Create a webhook:
.. In Slack, go to your organization’s app directory page.
.. Search for "Incoming WebHooks" and add a configuration.
. Choose or create a channel to post notifications to.
. Copy the webhook URL of your new configuration.
. In your `bat.yaml` file, create the `metadata` and `reporters` sections, if they do not already exist in the file. On a blank line, type `metadata:`. A few blank lines below that, type reporters:`.
. If you want to keep your webhook URL secret and you are running tests from a private location:
.. In Anypoint Secrets Manager, create a shared secret as a symmetric key that uses Base64 encoding.
... Open a secrets group or create a new one.
... Select Shared Secret on the left side of the screen.
... In the *Type* field, select *Symmetric Key*.
... In the *Key* field, paste your webhook encoded as a Base64 string.
... Paste the same Base64 string into the *Confirm Key* field.
.. Copy the name of the new shared secret.
.. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret.
.. In your `bat.yaml` file, add the Slack channel to the `metadata` section by adding this indented line:
+
[source,yaml]
----
  slack_channel: slack_channel
----
+
slack_channel:: Specify the name of the Slack channel that you want to send notifications to.
.. In your `bat.yaml` file, add Slack as a reporter by adding these indented lines to the `reporters` section:
+
[source,yaml]
----
  - type: Slack
    outFile: filename.json
    options:
      SLACK_WEBHOOK: <alias_for_the_shared_secret>
----
+
filename.json:: Specify a name for the output file to create.
alias_of_the_shared_secret:: Specify the alias that you used for the secret for the service key when you ran the `bat grant` command. The alias must be between carets.
. If you do not want to keep your webhook URL secret, add Slack as a reporter in your `bat.yaml` file by adding these lines to the `reporter` section:
+
[source,yaml]
----
  - type: Slack
    outFile: filename.json
    options:
      SLACK_WEBHOOK: "webhook_URL"
----
+
filename.json:: Specify a name for the output file to create.
webhook_URL:: Specify the URL of the webhook.


== Sumo Logic

To use Sumo Logic, you create a collection and specify it in the bat.yaml. The collection can be shared with other tests or used only as a monitor. At the end of each execution, BAT generates a post to SUMO that sends the trade-off information of requests and responses that were executed during the test. This enables you to see expected results and how the test behaves.

You must provide the endpoint of the collection.

You can use BAT to post a log in the specified collection, and create dashboards.

=== To Integrate Sumo and BAT

. In Sumo Logic, use the Setup Wizard to Set Up Streaming Data.
+
. Choose Your Custom App > HTTP Source or All Other Sources > HTTP Source and fill out the source category.
. Copy the HTTP source and implement the Sumo Logic integration in your bat.yaml file:
+
----
reporters:
  - type: SumoLogic
    outfile: SumoLogic.json
    options:
      SUMO_ENDPOINT: <your endpoint URL>
----
+
The SUMO_ENDPOINT is, for example:
+
`+https://endpoint1.collection.us2.sumologic.com/...+`
+
In a few moments, the test results appear in Sumo Logic under Log Search.

== Custom Post Report

BAT publishes the result.json with a post to the URL specified in the bat.yaml file. You can add headers if necessary.

[source,yaml,linenums]
----
reporters:
  - type: Custom
    options:
      URL: "http://www.httpbin.org/post"
      HEADERS: "'Authorization':'Bearer token','Content-Type':'application/json'"
----

== About Local Reports

BAT generates basic types of reports locally in JSON and HTML. When you execute tests, the path to the reports appears in the output.

Example:

[source,yaml,linenums]
----
Reporter: /var/folders/vz/56jp75d941592x_1d8mfy9f40000gn/T/bat_report_20180320121736.json
Reporter: /var/folders/vz/56jp75d941592x_1d8mfy9f40000gn/T/bat_report_20180320121736.html
----

== To Configure Local Report Generation

In the bat.yaml file, specify a `type` field to generate local reports. For example:

[source,yaml,linenums]
----
reporters:
  - type: JSON
    outFile: JSON.json
  - type: HTML
    outFile: HTML.html
  - type: JUnit
    outFile: JUnit.xml
----

== To Create a Local Custom Report

You can generate a custom report based on a DataWeave transformation that is specified in the bat.yaml using the `file` keyword.

[source,yaml,linenums]
----
reporters:
  - type: Local
    file: reporter/transform.dwl
    outFile: local.json
----

The transform.dwl file contains the following code:

[source,dataweave,linenums]
----
%dw 2.0
output application/json
var result = if (payload.result.pass[0]) " is ok" else " failed"
---
{
    result: "The suite <" ++ payload.name ++ "> with assertion <" ++ payload.result[0].name ++ ">" ++ result
}
----

And the result is:

[source,dataweave,linenums]
----
{
  "result": "The suite <Hello world suite> with assertion <answer 200> is ok"
}
----

== Email

To email test reports that indicate failures, specify any email addresses that you want to send reports to. You can send reports to one or more email addresses, separating multiple email addresses with semicolons. Each report includes the name of the suite in which the error occurs and a list of the statements. Reports are emailed only for tests created in Anypoint Functional Monitoring in Anypoint Platform, not for tests created with the BAT CLI.

[source,yaml,linenums]
----
reporters:
  - type: Email
    options:
      EMAILS: test@example.com;other@example.com;youremail@example.com
----
