= About API Functional Monitoring
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: afm-delete-test.adoc

:imagesdir: ../assets/images

API Functional Monitoring (AFM) enables developers and administrators to assure the quality and reliability of APIs that are being used in application networks. AFM enables the monitoring of the functional behavior and performance of APIs, throughout the API lifecycle, in testing and production environments.

You can monitor both public and private APIs:

* _Public_ APIs are APIs deployed are accessible by anyone who is connected to the internet.
* _Private_ APIs are APIs deployed in Anypoint Virtual Private Cloud in CloudHub and accessible only to people who are in your private network.

For each API or set of interdependent APIs that you want to monitor, you create a _monitor_, which consists of a test, one or more schedules that run the test at intervals, and information for connecting to any third-party applications that you set up to notify you of test failures.

A test consists of:

* One or more combinations of HTTP methods and endpoints
+
For example, in a single test, you might send a request to the endpoint `\https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1` by using the HTTP method GET and a request to the endpoint `\https://deckofcardsapi.com/api/deck/<deck_ID>/shuffle/` also by using the GET method.

* One or more assertions
+
By default, the assertion for a test is "Status code must equal 200". However, you can change that assertion and add more. For example, you might add the assertion "Response header Cache-Control must equal `max-age=604800`".

* Optional HTTP request headers
+
By default, no headers are included in requests sent to endpoints. However, you can include any of the headers that AFM supports.

Tests are executed from either public locations or private locations.

* A _public location_ is a region (which you can think of as a resource pool) that is shared with other MuleSoft customers.
+
Examples of such regions are `us-east-1`, `us-east-2`, and `eu-central-1`.

* A _private location_ is a worker that runs in a CloudHub environment that is associated with an instance of Anypoint Virtual Private Cloud.


== Two Different Ways to Create Monitors

There are two ways that you can perform functional testing:

* Write tests manually and then schedule them with the Blackbox Automated Testing (BAT) CLI.
+
Test cases are all defined with a common, declarative, and easy-to-use behavior-description language. The language is based on the DataWeave language and follows the “given-when-then” approach to describe behavior in terms of conditions and expected outcomes.
* Create monitors in the *Functional Monitoring* section of Anypoint Monitoring. You can upload as monitors any testing projects that you wrote manually.

== See also

* xref:afm-in-anypoint-platform.adoc[API Functional Monitoring in Anypoint Platform]
* xref:bat-top.adoc[API Functional Monitoring with the BAT CLI]
* xref:afm-supported-http-request-headers.adoc[Supported HTTP Request Headers]
