// tag::config-in-secrets-mgr[]

[[configure-secret]]
= Configure a Secret in Anypoint Secret Manager

If you want to keep sensitive information secret and you are running tests from a private location, in Anypoint Secrets Manager, create a shared secret as a symmetric key. If the sensitive information that you want to store as a shared secret is currently in plain text, then you must encode it in Base64 before you create the secret.

To configure a shared secret:

. Open a secrets group or create a new one. The group must be created in the same environment that you are using in the BAT CLI. 
+
To find out which environment you are currently using in the BAT CLI:

.. Run the command `bat whoami`. 
+
The output has the ID for the environment. 

.. Run the command `bat environment ls` to list the environments to which you have access. 

.. Match the ID from the `bat whoami` command with one of the environments listed. 

.. If you need to switch to the environment that your secrets group is in, run the command `bat environment switch name`, where `name` is the name of the environment.

. Select *Shared Secret*.
. In the *Type* field, select *Symmetric Key*.
. In the *Key* field, paste the sensitive information encoded as a Base64 string.
. Paste the Base64 string into the *Confirm Key* field.

// end::config-in-secrets-mgr[]

// tag::grant-access-to-secret[]

[[grant-access-to-secret]]
= Grant Your Monitor Access to the Secret

After you modify your monitor to add the secret information, grant the monitor access to the secret. 

To grant a monitor access to the secret:

. Copy the name of the new shared secret obtained in <<configure-secret>>.
. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret. When you run this command, the BAT CLI creates a section named `secrets` in your test suite's `bat.yaml` file, if the section does not already exist. In that section, the BAT CLI adds these indented lines:
+
----
alias:
 secretId: "secret-ID"
----
+
* `alias`: This is the alias that you specified in the `bat grant` command.
* `secret-ID`: This is the ID of the secret within Anypoint Secrets Manager. This ID does not appear in ASM, so there is no way for someone looking in your `bat.yaml` file to associate the ID with any particular secret. The BAT CLI uses this ID to look up the secret that you associated with the alias.

// end::grant-access-to-secret[]

// tag::deploy-monitor[]

[[deploy-updated-monitor]]
= Deploy the Updated Monitor

After completing the prior procedures, upload your monitor as documented in xref:afm-upload-monitor.adoc#upload-a-monitor[Upload a Monitor].

// end::deploy-monitor[]