Partials reused in index.adoc and specific feature topics

// tag::afm-monitors[]

[[afm-monitors]]
= Monitors

A _monitor_ is a repeating schedule of one or more tests, referred to as a _suite_.

// end::afm-monitors[]

// tag::afm-tests[]

[[afm-tests]]
= Tests

Tests are run in monitors on a defined schedule. Test cases are defined using <<afm-bdd>>, a common, declarative, and easy-to-use behavior-description language.

// end::afm-tests[]

// tag::afm-schedules[]

[[afm-schedules]]
= Schedules

The tests in monitors are run on schedules.

// end::afm-schedules[]

// tag::afm-bb-testing[]

[[afm-bb-testing]]
= Black Box Testing

This type of testing validates the overall behavior of an API and its real/live dependencies as a whole, based purely on inputs and outputs (i.e. without knowing or altering the API internals - no simulation or mocking).

// end::afm-bb-testing[]

// tag::afm-wb-testing[]

[[afm-wb-testing]]
= White Box Testing

This type of testing validates the behavior of individual APIs against the understanding of how their internals work. As part of this type of testing, you mock and simulate dependencies (for example, back-end systems and other APIs).

// end::afm-wb-testing[]

// tag::afm-runtime-monitoring[]

[[afm-runtime-monitoring]]
= Runtime Monitoring

This type of monitoring ensures that deployed APIs are operating within expected performance in production environments. It makes use of behavioral test cases that use real inputs and expected outputs and exercise dependencies, as in black-box testing.

// end::afm-runtime-monitoring[]

// tag::afm-private-locations[]

[[afm-private-locations]]
= Private Locations

A private location is a worker that runs in an environment that is associated with an instance of Anypoint VPC in CloudHub 1.0 or a private space in Cloudhub 2.0. You can run tests against APIs that are accessible only within the private location. 

// end::afm-private-locations[]

// tag::afm-public-locations[]

[[afm-public-locations]]
= Public Locations

A region (which you can think of as a resource pool) that is shared with other MuleSoft customers. Examples of such regions are `us-east-1`, `us-east-2`, and `eu-central-1`.

// end::afm-public-locations[]

// tag::afm-private-apis[]

[[afm-private-apis]]
= Private APIs

Private APIs are APIs with endpoints that are accessible only within your network.

// end::afm-private-apis[]

// tag::afm-public-apis[]

[[afm-public-apis]]
= Public APIs

APIs with endpoints that are exposed to the open internet. Tests of such endpoints are run by workers that themselves run in public locations or private locations.

// end::afm-public-apis[]

// tag::afm-bdd[]

[[afm-bdd]]
= Behavior Driven Development (BDD) Language

The BDD language is based on DataWeave and follows the “given-when-then” approach to describe behavior in terms of conditions and expected outcomes.

// end::afm-bdd[]