// Used in afm-mask-info-in-monitors.adoc and bat-reporting-task.adoc

// tag::secrets-limitations[]

[[secrets-limitations]]
= Limitations

* Functional Monitoring works only with symmetric key shared secret types from Anypoint Secrets Monitor. If you use any other types,   all previously used shared secrets are no longer populated.

* You can use aliases for shared secrets in a test suite only if you plan to run that test suite from a private location.

// end::secrets-limitations[]

// tag::config-in-secrets-mgr[]

[[configure-secret]]
= Configure a Secret in Anypoint Secret Manager

To keep sensitive information secret in tests you run from a private location, create a shared secret as a symmetric key in Secrets Manager. If the sensitive information that you want to store as a shared secret is currently in plain text, encode it in Base64 before you create the secret.

To configure a shared secret:

. Open a secrets group or create a new one. Create the group in the same environment that you are using in the BAT CLI. 
+
To find out which environment you are currently using in the BAT CLI:

.. Run the command `bat whoami`. 
+
The output has the ID for the environment. 

.. Run the command `bat environment ls` to list the environments to which you have access. 

.. Match the ID from the `bat whoami` command with one of the environments listed. 

.. If you need to switch to the environment that your secrets group is in, run the command `bat environment switch name`, where `name` is the name of the environment.

. Select *Shared Secret*.
. In the *Type* field, select *Symmetric Key*.
. In the *Key* field, paste the sensitive information encoded as a Base64 string.
. Paste the Base64 string into the *Confirm Key* field.

// end::config-in-secrets-mgr[]

// tag::grant-access-to-secret[]

[[grant-access-to-secret]]
= Grant Your Monitor Access to the Secret

After you modify your monitor to add the secret information, grant the monitor access to the secret. At runtime, BAT CLI looks up the shared secrets using the aliases.

To grant a monitor access to the secret:

. Copy the name of the new shared secret obtained in <<configure-secret>>.
. At a command prompt, run the `bat grant` command, specifying an alias for the shared secret. When you run this command, the BAT CLI creates a section named `secrets` in your test suite's `bat.yaml` file, if the section does not already exist. In that section, the BAT CLI adds these indented lines:
+
----
alias:
 secretId: "secret-ID"
----
+
* `alias`: The alias that you specified in the `bat grant` command.
* `secret-ID`: The ID of the secret within Anypoint Secrets Manager. This ID does not appear in ASM, so there is no way for someone looking in your `bat.yaml` file to associate the ID with any particular secret. The BAT CLI uses this ID to look up the secret that you associated with the alias.

// end::grant-access-to-secret[]

// tag::deploy-monitor[]

[[deploy-updated-monitor]]
= Deploy the Updated Monitor

After completing the prior procedures, upload your monitor as documented in xref:afm-upload-monitor.adoc#upload-a-monitor[Upload a Monitor].

// end::deploy-monitor[]